import { Lionize as Task } from 'src/app/shared/models/tasks/Lionize';
import { Lionize as Identity } from 'src/app/shared/models/identity/Lionize';
export type SignInRequest = Task.TaskManagement.ApiModels.V1.SignInRequest;
export type SignInResponse = Task.TaskManagement.ApiModels.V1.SignInResponse;
export type SignOutRequest = Task.TaskManagement.ApiModels.V1.SignOutRequest;
export type SignOutResponse = Task.TaskManagement.ApiModels.V1.SignOutResponse;
export type RefreshTokenRequest = Task.TaskManagement.ApiModels.V1.RefreshTokenRequest;
export type RefreshTokenResponse = Task.TaskManagement.ApiModels.V1.RefreshTokenResponse;
export type SignUpRequest = Identity.IdentityManagementService.ApiModels.SignUpRequest;
export type SignUpResponse = Identity.IdentityManagementService.ApiModels.SignUpResponse;