---
namespace:
  - Lionize
  - TaskManagement
  - ApiModels
  - V1
models:
  - name: SignInRequest
    fields:
      - name: Username
        type: string
      - name: Password
        type: string
  - name: SignInResponse
    fields:
      - name: AccessToken
        type: string
      - name: IdentityToken
        type: string
      - name: TokenType
        type: string
      - name: RefreshToken
        type: string
      - name: IsError
        type: boolean
      - name: ErrorMessage
        type: string
  - name: BacklogTask
    fields:
      - name: ID
        type: string
      - name: Name
        type: string
      - name: Description
        type: string
      - name: Order
        type: integer
      - name: Subtasks
        type: SubTask
        array: true
  - name: SubTask
    fields:
      - name: ID
        type: integer
      - name: Name
        type: string
      - name: Order
        type: integer
...